USE [master]
GO

/****** Object:  Database [WebApp]    Script Date: 4/9/2018 8:11:35 PM ******/
DROP DATABASE [WebApp]
GO

/****** Object:  Database [WebApp]    Script Date: 4/9/2018 8:11:35 PM ******/
CREATE DATABASE [WebApp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WebApp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLSERVER\MSSQL\DATA\WebApp.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'WebApp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLSERVER\MSSQL\DATA\WebApp_log.ldf' , SIZE = 1536KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [WebApp] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WebApp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WebApp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WebApp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WebApp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WebApp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WebApp] SET ARITHABORT OFF 
GO

ALTER DATABASE [WebApp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WebApp] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [WebApp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WebApp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WebApp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WebApp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WebApp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WebApp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WebApp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WebApp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WebApp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WebApp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WebApp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WebApp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WebApp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WebApp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WebApp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WebApp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WebApp] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [WebApp] SET  MULTI_USER 
GO

ALTER DATABASE [WebApp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WebApp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WebApp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WebApp] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [WebApp] SET  READ_WRITE 
GO

